### ISSUE TITLE
Solr Removal - stats portal

### ISSUE THREAD

**Issue by kjgarza** [datacite/stats-portal#23]
Refractor to call API instead of Solr

**Comment by kjgarza** [comment]
Most of the work has been completed. but there are some issue with the final implementation that need to be fixed.

- [ ] Cache of Ajax queries is not working. 
- [ ] The request for DOI production stats  are very slow. We could:
     -  Server side caching
     -  Change the way the aggregation are made to include pagination. The stats portal now supports that. IT was not supported before.
     - Client side cachin.
- [ ] Link to filter resilutions is missing.

**Comment by kjgarza** [comment]
Using server side caching we reduced the request time from the *seconds* to `milliseconds` https://github.com/datacite/lupo/commit/c2f9c749148921ca06df6717a6c2b6f84693a51f

**Comment by mfenner** [comment]
More work is needed on making the request for DOI stats faster, server caching is not the best approach (e.g. because it is only refreshed every 24 hours).

**Comment by kjgarza** [comment]
released on https://github.com/datacite/stats-portal/releases/tag/2.0.11
