### ISSUE TITLE
Cosmetic issues with new layout

### ISSUE THREAD

**Issue by mfenner** [datacite/stats-portal#28]
- [x] add space between table and footer
- [x]  Wording in tabs (should be "Registrations by Member", etc.)
- [x]  Resolutions tab includes old layout with duplication and inconsistencies
- [x]  "This month" and "Registered" are not shown in full.
- [x]  hover over tabs should always be pointer, as it is a clickable link
- [x]  clicking on year (e.g. 2019) or this month should sort that column, in descending order for the first click
- [x]  add favicon

Child to #23.

**Comment by mfenner** [comment]
[ ] selected tab should have different color

**Comment by kjgarza** [comment]
tab toggle added in 6a73fb1b17a23a5101597ea3fd0a3cc61b71c6a5

**Comment by kjgarza** [comment]
added further feedback in https://github.com/datacite/stats-portal/commit/2aa58a591cbf788277d42a90a4a3a0092830b4de
