### ISSUE TITLE
Evaluate Performance of Stats portal with ES Calls

### ISSUE THREAD

**Issue by kjgarza** [datacite/stats-portal#30]
Overall we have replicated similar response times in the stats portal with a slight increase on the response time when showing full lists. In filtering results the new queries outperform the old SOLR calls. N.B. The new calls are not caching any part of the response.

The following response time comparison are between the Production system (OLD) using the old calls and the localhost pointing to the Production API. 

All providers load
New = 8-10sec
Old = 2-3sec

All clients load
New = 11-13sec
Old = 7-8sec

All prefixes load
New = 8.5sec
Old = 8.5-9.2sec

filtering by BL
New = 1-2sec
Old = 3.5-4 sec

filtering by BL.CCDC
New = 1sec
Old = 4sec

Part of the improvement could be attributed to the lack of reloading the whole page, as the new Stats portal website only reloads the table content.

child #23

**Comment by mfenner** [comment]
I suggest a more systematic review, where we take a closer took at where the time is spent, and whether we can optimize. Using a tool such as https://github.com/igorkasyanchuk/benchmark_methods.

**Comment by kjgarza** [comment]
It is complicated to compare the new Stats API calls to the previous implmentation as the same results were obtained with a combination of different requests. For example obtaining all the information for clients stats was obtained by a combination of 7 separated API calls. In the new implementation we take advatage of ES aggreagtion and we obtain the same data in 1 single API call. One can, however compare load time of the websites.

| Loading times (sec.) |Old stats Portal  | New stats Portal  |
|--|--|-- |
| all providers | 1-2   | 8-17 |
| all clients | 7-8  | 11-13  |
| all prefixes | 8.8 - 9.2  | 8.5 |
| filtered provider | 3.5-4 |  1-2|
| filtered client | 4 |1|


Alternatively, another comparison we can make is to compare the Stats API calls (`/totals`) with other REST API calls. Below we compare them with calling the `/dois` endpoint and the same endpoint for 100 dois.

|  | Avg. Latency (sec.)  | 
|--|--|
| /dois | 15.57s | 
| /dois?page[size]=100 | 17.20s |
| /clients/totals | 15.96s | 
| /providers/totals | 14.62s  | 
| /prefixes/totals | 15.10s |

this probably indicates that there is something in the current implementation that affects all requests.

All benchmark in
https://docs.google.com/file/d/1tuzQivkVjXrxPBZ97PwayFQo244kDx_-/edit

**Comment by kjgarza** [comment]
One of the reasons why all the calls take very similar times is that they all use DOI.query to obtian the aggregation. So far we have been overloading the aggregation methods for DOI queries and that is making the API calls slower.

I have separated that for Stats API calls and removed from the /dois calls. 
https://github.com/datacite/lupo/commit/76407c0028286e7448ae3e94f1356b644751ba49

In the process, I improved response times for all calls. Maybe we should consider removing all those aggregations


|  | Avg. Latency (sec.)  | 
|--|--|
| /dois | 8.55s | 
| /dois?page[size]=100 | 9.81s |
| /clients/totals | 12.04s | 
| /providers/totals | 8.17s  | 
| /prefixes/totals | 8.90s |

We seem however to have reached a time limit barrier at the 8sec mark.
Reminder: none of these calls is cached.

**Comment by mfenner** [comment]
We should look at the actual times spent in each stop so that we can identify the bottlenecks. We have said to not complete this work until after the DataCite General Assembly. There is also an action item for me to look into this after our last developer meeting.

**Comment by mfenner** [comment]
@kjgarza I can take this work over from you, as this relates to the action item assigned to me in our recent in-person meeting in Berlin.

**Comment by mfenner** [comment]
Addressed in datacite/lupo#224.
